function [covarEst,uEst] = pred_step(uPrev,covarPrev,angVel,acc,dt)
%covarPrev and uPrev are the previous mean and covariance respectively
%angVel is the angular velocity
%acc is the acceleration
%dt is the sampling time
    
    x = uPrev;    % state

    u = vertcat(angVel,acc);    % input

    p = x(1:3); % position
    q = x(4:6); % orientation
    p_dot = x(7:9); % velocity
    b_g = x(10:12); % gyroscope bias
    b_a = x(13:15); % accelerometer bias

    G = [1 0 -sin(x(5));0 cos(x(4)) cos(x(5))*sin(x(4));0 -sin(x(4)) cos(x(5))*cos(x(4))];

    eul = [x(6) x(5) x(4)];
    R = eul2rotm(eul);

    g = [0;0;-9.81];

    n_g = zeros(3,1);
    n_a = zeros(3,1);
    n_bg = zeros(3,1);
    n_ba = zeros(3,1);
    n = vertcat(n_g,n_a,n_bg,n_ba); % noise

    x_dot_noise0 = [p_dot;G\(angVel-b_g-n_g);g+R*(acc-b_a-n_a);n_bg;n_ba];
    
    A_t = [0, 0, 0,                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                           0, 1, 0, 0,                                                                          0,                                                    0,                                                    0,                0,                                           0,                                           0;
           0, 0, 0,                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                           0, 0, 1, 0,                                                                          0,                                                    0,                                                    0,                0,                                           0,                                           0;
           0, 0, 0,                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                           0, 0, 0, 1,                                                                          0,                                                    0,                                                    0,                0,                                           0,                                           0;
           0, 0, 0, -(n(2)*cos(x(4))*sin(x(5)) - u(2)*cos(x(4))*sin(x(5)) + x(11)*cos(x(4))*sin(x(5)) - n(3)*sin(x(4))*sin(x(5)) + u(3)*sin(x(4))*sin(x(5)) - x(12)*sin(x(4))*sin(x(5)))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)), (n(1)*sin(x(4))^2*sin(x(5)) - u(1)*sin(x(4))^2*sin(x(5)) + x(10)*sin(x(4))^2*sin(x(5)) - n(3)*cos(x(4))*cos(x(5)) + u(3)*cos(x(4))*cos(x(5)) - x(12)*cos(x(4))*cos(x(5)) - n(2)*cos(x(5))*sin(x(4)) + u(2)*cos(x(5))*sin(x(4)) - x(11)*cos(x(5))*sin(x(4)) + n(1)*cos(x(4))^2*sin(x(5)) - u(1)*cos(x(4))^2*sin(x(5)) + x(10)*cos(x(4))^2*sin(x(5)))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)) - (sin(x(5))*(n(3)*cos(x(4))*sin(x(5)) - u(3)*cos(x(4))*sin(x(5)) + x(12)*cos(x(4))*sin(x(5)) + n(2)*sin(x(4))*sin(x(5)) - u(2)*sin(x(4))*sin(x(5)) + x(11)*sin(x(4))*sin(x(5)) + n(1)*cos(x(4))^2*cos(x(5)) - u(1)*cos(x(4))^2*cos(x(5)) + x(10)*cos(x(4))^2*cos(x(5)) + n(1)*cos(x(5))*sin(x(4))^2 - u(1)*cos(x(5))*sin(x(4))^2 + x(10)*cos(x(5))*sin(x(4))^2))/(cos(x(5))^2*(cos(x(4))^2 + sin(x(4))^2)),                                                                                                                                                           0, 0, 0, 0, -(cos(x(5))*cos(x(4))^2 + cos(x(5))*sin(x(4))^2)/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)), -(sin(x(4))*sin(x(5)))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)), -(cos(x(4))*sin(x(5)))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)),                0,                                           0,                                           0;
           0, 0, 0,                                                            (n(3)*cos(x(4)) - u(3)*cos(x(4)) + x(12)*cos(x(4)) + n(2)*sin(x(4)) - u(2)*sin(x(4)) + x(11)*sin(x(4)))/(cos(x(4))^2 + sin(x(4))^2),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                           0, 0, 0, 0,                                                                          0,                     -cos(x(4))/(cos(x(4))^2 + sin(x(4))^2),                      sin(x(4))/(cos(x(4))^2 + sin(x(4))^2),                0,                                           0,                                           0;
           0, 0, 0,                                                 -(n(2)*cos(x(4)) - u(2)*cos(x(4)) + x(11)*cos(x(4)) - n(3)*sin(x(4)) + u(3)*sin(x(4)) - x(12)*sin(x(4)))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -(sin(x(5))*(n(3)*cos(x(4)) - u(3)*cos(x(4)) + x(12)*cos(x(4)) + n(2)*sin(x(4)) - u(2)*sin(x(4)) + x(11)*sin(x(4))))/(cos(x(5))^2*(cos(x(4))^2 + sin(x(4))^2)),                                                                                                                                                           0, 0, 0, 0,                                                                          0,           -sin(x(4))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)),           -cos(x(4))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)),                0,                                           0,                                           0;
           0, 0, 0,                                        - (sin(x(4))*sin(x(6)) + cos(x(4))*cos(x(6))*sin(x(5)))*(n(5) - u(5) + x(14)) - (cos(x(4))*sin(x(6)) - cos(x(6))*sin(x(4))*sin(x(5)))*(n(6) - u(6) + x(15)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       cos(x(6))*sin(x(5))*(n(4) - u(4) + x(13)) - cos(x(4))*cos(x(5))*cos(x(6))*(n(6) - u(6) + x(15)) - cos(x(5))*cos(x(6))*sin(x(4))*(n(5) - u(5) + x(14)), (cos(x(4))*cos(x(6)) + sin(x(4))*sin(x(5))*sin(x(6)))*(n(5) - u(5) + x(14)) - (cos(x(6))*sin(x(4)) - cos(x(4))*sin(x(5))*sin(x(6)))*(n(6) - u(6) + x(15)) + cos(x(5))*sin(x(6))*(n(4) - u(4) + x(13)), 0, 0, 0,                                                                          0,                                                    0,                                                    0, -cos(x(5))*cos(x(6)),   cos(x(4))*sin(x(6)) - cos(x(6))*sin(x(4))*sin(x(5)), - sin(x(4))*sin(x(6)) - cos(x(4))*cos(x(6))*sin(x(5));
           0, 0, 0,                                          (cos(x(6))*sin(x(4)) - cos(x(4))*sin(x(5))*sin(x(6)))*(n(5) - u(5) + x(14)) + (cos(x(4))*cos(x(6)) + sin(x(4))*sin(x(5))*sin(x(6)))*(n(6) - u(6) + x(15)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       sin(x(5))*sin(x(6))*(n(4) - u(4) + x(13)) - cos(x(4))*cos(x(5))*sin(x(6))*(n(6) - u(6) + x(15)) - cos(x(5))*sin(x(4))*sin(x(6))*(n(5) - u(5) + x(14)), (cos(x(4))*sin(x(6)) - cos(x(6))*sin(x(4))*sin(x(5)))*(n(5) - u(5) + x(14)) - (sin(x(4))*sin(x(6)) + cos(x(4))*cos(x(6))*sin(x(5)))*(n(6) - u(6) + x(15)) - cos(x(5))*cos(x(6))*(n(4) - u(4) + x(13)), 0, 0, 0,                                                                          0,                                                    0,                                                    0, -cos(x(5))*sin(x(6)), - cos(x(4))*cos(x(6)) - sin(x(4))*sin(x(5))*sin(x(6)),   cos(x(6))*sin(x(4)) - cos(x(4))*sin(x(5))*sin(x(6));
           0, 0, 0,                                                                                                  cos(x(5))*sin(x(4))*(n(6) - u(6) + x(15)) - cos(x(4))*cos(x(5))*(n(5) - u(5) + x(14)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               cos(x(5))*(n(4) - u(4) + x(13)) + cos(x(4))*sin(x(5))*(n(6) - u(6) + x(15)) + sin(x(4))*sin(x(5))*(n(5) - u(5) + x(14)),                                                                                                                                                           0, 0, 0, 0,                                                                          0,                                                    0,                                                    0,          sin(x(5)),                            -cos(x(5))*sin(x(4)),                            -cos(x(4))*cos(x(5));
           0, 0, 0,                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                           0, 0, 0, 0,                                                                          0,                                                    0,                                                    0,                0,                                           0,                                           0;
           0, 0, 0,                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                           0, 0, 0, 0,                                                                          0,                                                    0,                                                    0,                0,                                           0,                                           0;
           0, 0, 0,                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                           0, 0, 0, 0,                                                                          0,                                                    0,                                                    0,                0,                                           0,                                           0;
           0, 0, 0,                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                           0, 0, 0, 0,                                                                          0,                                                    0,                                                    0,                0,                                           0,                                           0;
           0, 0, 0,                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                           0, 0, 0, 0,                                                                          0,                                                    0,                                                    0,                0,                                           0,                                           0;
           0, 0, 0,                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                           0, 0, 0, 0,                                                                          0,                                                    0,                                                    0,                0,                                           0,                                           0];
 
    U_t = [                                                                         0,                                                    0,                                                    0,                0,                                           0,                                           0, 0, 0, 0, 0, 0, 0;
                                                                                    0,                                                    0,                                                    0,                0,                                           0,                                           0, 0, 0, 0, 0, 0, 0;
                                                                                    0,                                                    0,                                                    0,                0,                                           0,                                           0, 0, 0, 0, 0, 0, 0;
            -(cos(x(5))*cos(x(4))^2 + cos(x(5))*sin(x(4))^2)/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)), -(sin(x(4))*sin(x(5)))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)), -(cos(x(4))*sin(x(5)))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)),                0,                                           0,                                           0, 0, 0, 0, 0, 0, 0;
                                                                                    0,                     -cos(x(4))/(cos(x(4))^2 + sin(x(4))^2),                      sin(x(4))/(cos(x(4))^2 + sin(x(4))^2),                0,                                           0,                                           0, 0, 0, 0, 0, 0, 0;
                                                                                    0,           -sin(x(4))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)),           -cos(x(4))/(cos(x(5))*(cos(x(4))^2 + sin(x(4))^2)),                0,                                           0,                                           0, 0, 0, 0, 0, 0, 0;
                                                                                    0,                                                    0,                                                    0, -cos(x(5))*cos(x(6)),   cos(x(4))*sin(x(6)) - cos(x(6))*sin(x(4))*sin(x(5)), - sin(x(4))*sin(x(6)) - cos(x(4))*cos(x(6))*sin(x(5)), 0, 0, 0, 0, 0, 0;
                                                                                    0,                                                    0,                                                    0, -cos(x(5))*sin(x(6)), - cos(x(4))*cos(x(6)) - sin(x(4))*sin(x(5))*sin(x(6)),   cos(x(6))*sin(x(4)) - cos(x(4))*sin(x(5))*sin(x(6)), 0, 0, 0, 0, 0, 0;
                                                                                    0,                                                    0,                                                    0,          sin(x(5)),                            -cos(x(5))*sin(x(4)),                            -cos(x(4))*cos(x(5)), 0, 0, 0, 0, 0, 0;
                                                                                    0,                                                    0,                                                    0,                0,                                           0,                                           0, 1, 0, 0, 0, 0, 0;
                                                                                    0,                                                    0,                                                    0,                0,                                           0,                                           0, 0, 1, 0, 0, 0, 0;
                                                                                    0,                                                    0,                                                    0,                0,                                           0,                                           0, 0, 0, 1, 0, 0, 0;
                                                                                    0,                                                    0,                                                    0,                0,                                           0,                                           0, 0, 0, 0, 1, 0, 0;
                                                                                    0,                                                    0,                                                    0,                0,                                           0,                                           0, 0, 0, 0, 0, 1, 0;
                                                                                    0,                                                    0,                                                    0,                0,                                           0,                                           0, 0, 0, 0, 0, 0, 1];

    n_g = [0.003;0.003;0.003];
    n_a = [0.003;0.003;0.003];
    n_bg = [0.00001;0.00001;0.00001];
    n_ba = [0.00001;0.00001;0.00001];
    n = vertcat(n_g,n_a,n_bg,n_ba); % noise

    F_t = eye(15) + dt*A_t;
    V_t = U_t;
    Q_t = diag(n);
    Q_d = Q_t*dt;                              

    uEst = uPrev+dt*x_dot_noise0;
    covarEst = F_t*covarPrev*(F_t.')+V_t*Q_d*(V_t.');
end